### ISSUE TITLE
[BUG] 카운트 다운 화면에서 화면잠금을 했다가 키면 숫자가 10초부터 빠르게 감소하는 버그

### ISSUE THREAD

**Issue by juhwankim-dev** [Next-Room/NextRoom-Android#39]
## AS-IS

1. 테마를 선택하고 10초 카운트 다운 화면으로 넘어온다
2. 화면을 잠그고 잠시 대기한다.
3. 화면을 킨다
4. 카운트가 다시 10초부터 시작하고, 숫자가 빠르게 감소한다.

## TO-BE

화면을 잠그면 시간을 멈추거나
화면을 잠궈도 시간이 정상적으로 흘러가게 변경한다.

기획상 두 방법 다 상관없으며
구현하기 더 편한 방법으로 수정한다.

## 해야할 일

- [ ] TODO1

**Comment by juhwankim-dev** [comment]
백로그에 등록한다는 느낌으로 올려두었으며
메인 피쳐 개발 이후 시간이 남으면 여유가 되는 사람이 수정

**Comment by mangbaam** [comment]
작업 시작합니다~! @juhwankim-dev 

### 작업 방향

-  화면을 잠궈도 시간이 정상적으로 흘러가는 방향으로!

### 이유

- 알바생이 게임을 시작한 후 카운트 다운이 되는 화면에서 힌트폰을 건냈을 때 손님은 힌트를 바로 사용하지 않을 것이라서 폰을 받자마자 습관처럼 화면을 잠글 수도 있다. 이 상황이라면 게임 진행 시간이 불일치 하게 된다.

### 주의할 점

- 화면이 꺼진 상태로 다른 화면으로 이동시켜서 타이머를 동작시킬 수 없으니 카운트다운 화면에서 화면을 끈 상황이라면 게임 화면의 플레이 시간을 보정해야 한다.
